### PR TITLE
Attempt to handle parsing errors from tree-sitter.

### PR DESCRIPTION
**Pull request by mjambon**
It looks like I didn't add the exception catcher at the right spot because the original exceptions aborts the program:
```
$ ./_build/install/default/bin/semgrep-core -lang ts -e x toto.ts
toto.ts:1:0: Fatal Error: Tree_sitter_run.Tree_sitter_error.Error(_)

Fatal error: exception Tree_sitter_run.Tree_sitter_error.Error(_)
```
... but at least it compiles.

Hopefully my conversion from the `Tree_sitter_run.Tree_sitter_error.t` is correct. I had to add a field for holding the entire "token" (region of the error), which populates the `str` field on the semgrep side.

I'll let you take it from here or give me guidance on where/how to catch the exception.

This depends on https://github.com/returntocorp/ocaml-tree-sitter/pull/114

### CODE REVIEW

File: semgrep-core/dune [hunk 1]
```diff
@@ -1,5 +1,5 @@
 (env
 (dev
-(flags (:standard -w +42-52-6)))
+(flags (:standard -w -52-6)))
```
Comment (aryx) [inline semgrep-core/dune:3]: Why removing 42?

**Review by aryx — APPROVED** [review]
Ok i ll take it from there

File: semgrep-core/dune (hunk 1 above)
Comment (mjambon) [reply semgrep-core/dune:3]: This is what warning 42 tells us:
```
Warning 42: this use of x relies on type-directed disambiguation, it will not compile with OCaml 4.00 or earlier.
```

If 42 is enabled, the code gets really ugly when record fields from multiple modules need to be accessed. This was a problem for this code:

```ocaml
let mk_tree_sitter_error (err : Tree_sitter_run.Tree_sitter_error.t) =
  let start = err.start_pos in
  let loc = {
    PI.str = err.substring;
    charpos = 0; (* fake *)
    line = start.row + 1;
    column = start.column;
    file = err.file.name;
  } in
  Error_code.({ loc; typ = ParseError; sev = Error })
```
With warning 42, we'd have to `open` 2 modules (`Tree_sitter_run.Tree_sitter_error` and `Tree_sitter_run.Src_file`), or access fields as `err.Tree_sitter_error.substring` in combination with `let open Tree_sitter_run in`, or create short module aliases... even though the compiler and the reader know exactly which type we're dealing with from the type annotation on the function argument.
